In [1]:
#construct a matrix below

import numpy as np

matrix=([[1, 0.2, 0.5],
         [0.2, 1, 0.8],
         [0.5, 0.8, 1]])

inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [3]:
#determinant of the matrix

import numpy as np
matrix=([[1, 0.2, 0.5],
         [0.2, 1, 0.8],
         [0.5, 0.8, 1]])

determinant_matrix = np.linalg.det(matrix)
print(determinant_matrix)

0.2299999999999999


In [7]:
#decomposing a matrix(eigen values)

import numpy as np
matrix=([[1, 0.2, 0.5],
         [0.2, 1, 0.8],
         [0.5, 0.8, 1]])

decomposed_matrix = np.linalg.eig(matrix)
print(decomposed_matrix)

EigResult(eigenvalues=array([2.04100779, 0.82188052, 0.13711169]), eigenvectors=array([[-0.43721717, -0.85359707, -0.28321933],
       [-0.59931898,  0.51133314, -0.61591816],
       [-0.67056536,  0.09955128,  0.73514055]]))


In [8]:
#transforming a matrix
import numpy as np

matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])

#transpose a matrix
transposed_matrix = np.transpose(matrix)

#print the original and transposed matrix

print("original matrix:")
print(matrix)
print("\nTransposed Mtrix:")
print(transposed_matrix)

original matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Transposed Mtrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
